version: "3.8"

services:
  websocket:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${WS_PORT}:${WS_PORT}" # Dynamically map external:internal port
    environment:
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - WS_PORT=${WS_PORT}
    restart: unless-stopped
